services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - adonis_app

  adonis_app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - 9229:9229
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD : true
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: romain
      MYSQL_PASSWORD: romain
    volumes:
      - mysql_volume:/var/lib/mysql

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379


volumes:
  mysql_volume:
  redis_volume: